version: '3'
services:
  #
  reverse-proxy:
    image: reverse-proxy
    ports:
      - 80:80
      - 443:443
    restart: always
  #
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - usersnetwork
    depends_on:
      - reverse-proxy
    restart: always

networks:
  usersnetwork:
    driver: bridge
