version: '3'
services:

  proxy_tunnel:
    image: danydodson/seesee_proxy_tunnel
    container_name: proxy_tunnel
    ports:
      - "2222:22"
    expose:
      - "2222"
    environment:
      - VIRTUAL_HOST=dev.seesee.space
      - LETSENCRYPT_HOST=dev.seesee.space

networks:
  default:
    external:
      name: sevrices_network
