sudo: required
services:
  - docker

before_install:
  - docker build -t danydodson/react-test -f ./seesee-client/Dockerfile.dev ./seesee-client

script:
  - docker run danydodson/react-test npm test -- --coverage

after_success:
  - docker build -t danydodson/seesee-seesee-client ./seesee-client
  - docker build -t danydodson/seesee-nginx-service ./nginx-service
  - docker build -t danydodson/seesee-server-service ./server-service
  - docker build -t danydodson/seesee-redis-service ./redis-service
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push danydodson/seesee-seesee-client
  - docker push danydodson/seesee-nginx-service
  - docker push danydodson/seesee-server-service
  - docker push danydodson/seesee-redis-service

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-306476627547
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
