###

GET https://api.github.com/users/danydodson HTTP/1.1

###

POST http://localhost:3050/user/signup HTTP/1.1
content-type: application/json

{
  "email": "danydodson@gmail.com",
  "password": "W2O7%%3R3QyDMue9",
  "password2": "W2O7%%3R3QyDMue9"
}

###

POST http://localhost:3050/user/signin HTTP/1.1
content-type: application/json

{
  "email": "dan@gmail.com",
  "password": "W2O7%%3R3QyDMue9"
}

###

GET http://localhost:3050/user HTTP/1.1
content-type: application/json
Authorization: {{token}}