version: '3'
services:
  postgres:
    container_name: postgres
    image: 'postgres'

  redis:
    image: 'redis'

  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx-service
    ports:
      - '3050:80'

  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: ./server-service
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=password
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432

  client:
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./seesee-client
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    container_name: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./redis-service
    volumes:
      - /app/node_modules
      - ./worker:/app
