version: '3'
services:

  # ==========================================#
  #  gateway/client                           #
  # ==========================================#

  gateway_client:
    container_name: gateway_client
    build: ./gateway/client
    restart: always
    environment:
      LISTINGS_SERVICE_URI: http://listings_service:7100
      USERS_SERVICE_URI: http://users_service:7101
    expose:
       - 3000
    ports:
      - 7000:7000
    depends_on:
      - listings_service
      - users_service
    networks:
      - api_network

  # ==========================================#
  #  services/nginx                           #
  # ==========================================#
  
  # nginx_service:
  #   container_name: nginx_service
  #   build: ./services/nginx
  #   restart: unless-stopped
  #   expose:
  #     - '80'
  #   ports:
  #     - '80:80'
  #   networks:
  #     - api_network

  # ==========================================#
  #  services/users                           #
  # ==========================================#
  
  users_service:
    container_name: users_service
    build: ./services/users/
    restart: unless-stopped
    environment:
      - DB_URI=mysql://root:password@users_service_db/db?charset=UTF8
    expose: 
      - 7101
    ports: 
      - 7101:7101
    depends_on:
      - users_service_db
    networks:
      - api_network

  # ==========================================#
  #  services/users:db                        #
  # ==========================================#

  users_service_db:
    container_name: users_service_db
    image: mysql:5.7.20
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 0.0.0.0:7201:3306
    networks:
      - api_network

  # ==========================================#
  #  services/listings                        #
  # ==========================================#

  listings_service:
    container_name: listings_service
    build: ./services/listings
    restart: unless-stopped
    environment:
      DB_URI: mysql://root:password@listings_service_db/db?charset=UTF8
    expose: 
      - 7100
    ports: 
      - 7100:7100
    depends_on:
      - listings_service_db
    networks:
      - api_network

  # ==========================================#
  #  services/listings:db                     #
  # ==========================================#

  listings_service_db:
    container_name: listings_service_db
    image: mysql:5.7.20
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 0.0.0.0:7200:3306
    networks:
      - api_network
      
# ==========================================#
#  global volumes                           #
# ==========================================#

# ==========================================#
#  global networks                          #
# ==========================================#
  
networks:
  api_network:
    driver: bridge