version: '3.8'

services:
  gateway:
    hostname: gateway
    build:
      context: gateway
      dockerfile: Dockerfile
    restart: always
    container_name: gateway
    image: danydodson/ss-gateway
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./gateway/nginx:/etc/nginx
      - ./gateway/certs/seesee.space:/etc/ssl/seesee.space
      - ./gateway/certs/voucher.seesee.space:/etc/ssl/voucher.seesee.space
    networks:
      - back-tier
    depends_on:
      - users-api
      - posts-api

  voucher:
    image: voucher/vouch-proxy
    restart: always
    container_name: voucher
    ports:
      - 9090:9090
    environment: 
      - VOUCH_DOMAINS=seesee.space
      - OAUTH_PROVIDER=oidc
      - OAUTH_CLIENT_ID=17a5v1sogv6t019643rid5q5mi
      - OAUTH_CLIENT_SECRET=1ou1ekob5rv5msbg2e858dd3mpt0qpdlfgi1mk6qamk5dsoatvug
      - OAUTH_AUTH_URL=https://seesee.auth.us-east-1.amazoncognito.com/oauth2/authorize
      - OAUTH_TOKEN_URL=https://seesee.auth.us-east-1.amazoncognito.com/oauth2/token
      - OAUTH_USER_INFO_URL=https://seesee.auth.us-east-1.amazoncognito.com/oauth2/userInfo
      - OAUTH_SCOPES='openid,email,profile'
      - OAUTH_CALLBACK_URL=http://vouch.seesee.space:9090/auth
    # volumes:
    #   - ./voucher/config:/config
    networks:
      - back-tier

  users-api:
    hostname: users-api
    build:
      context: users-api
      dockerfile: Dockerfile
    restart: always
    container_name: users-api
    image: danydodson/ss-users-api
    volumes:
      - ./users-api:/home/node/app
      - users-nm:/home/node/app/node_modules
    networks:
      - back-tier

  posts-api:
    hostname: posts-api
    build:
      context: posts-api
      dockerfile: Dockerfile
    restart: always
    container_name: posts-api
    image: danydodson/ss-posts-api
    volumes:
      - ./posts-api:/home/node/app
      - users-nm:/home/node/app/node_modules
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
    name: back-tier

volumes: 
  users-nm:
  posts-nm: