version: '3.8'
services:

  # ==========================================#
  #  webserver                                #
  # ==========================================#
  
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web_root:/var/www/html
      - ./services/node-sample/nginx:/etc/nginx/conf.d
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - node_sample
    networks:
      - app_network
      
  # ==========================================#
  #  services/node-sample                     #
  # ==========================================#

  node_sample:
    build:
      context: ./services/node-sample/
      dockerfile: Dockerfile
    image: node_sample
    container_name: node_sample
    restart: unless-stopped
    networks:
      - app_network

  # ==========================================#
  #  certbot                                  #
  # ==========================================#

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - web_root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email dany@dany.codes --agree-tos --no-eff-email --force-renewal -d seesee.space  -d www.seesee.space
      
# ==========================================#
#  global volumes                           #
# ==========================================#

volumes:

  certbot_etc:
  
  certbot_var:

  web_root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/seesee/services/node-sample/views/
      o: bind

  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/seesee/services/node-sample/dhparam/
      o: bind
  
# ==========================================#
#  global networks                          #
# ==========================================#
  
networks:
  app_network:
    driver: bridge