version: '3'
services:

  platform_pwa:
    build: platform/pwa
    container_name: platform_pwa
    restart: always
    ports:
      - '9090'
    volumes:
      - /home/node/app/node_modules
      - './platform/pwa:/home/node/app'
    networks:
      - app_network
    depends_on:
      - gateway_proxy
      
  gateway_proxy:
    build: gateway/proxy
    container_name: gateway_proxy
    restart: always
    ports:
      - '3050:80'
    networks:
      - app_network
    depends_on:
      - users_service
      - profiles_service
      - posts_service
      - gateway_client
      
  gateway_client:
    build: gateway/client
    container_name: gateway_client
    restart: always
    volumes:
      - /home/node/app/node_modules
      - './gateway/client:/home/node/app'
    networks:
      - app_network

  users_service:
    build: services/users
    container_name: users_service
    volumes:
      - /home/node/app/node_modules
      - './services/users:/home/node/app'
    networks:
      - app_network

  profiles_service:
    build: services/profiles
    container_name: profiles_service
    volumes:
      - /home/node/app/node_modules
      - './services/profiles:/home/node/app'
    networks:
      - app_network

  posts_service:
    build: services/posts
    container_name: posts_service
    volumes:
      - /home/node/app/node_modules
      - './services/posts:/home/node/app'
    networks:
      - app_network

networks:
  app_network: null
