version: '3.7'

services:

  gateway-nginx-proxy:
    container_name: gateway-nginx-proxy
    image: gateway-nginx-proxy:prod
    build:
      context: ./gateway/nginx-proxy
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    # depends_on:
    #   - services-test-api
    #   - gateway-web-client
    # command: sleep infinity
    # links:
      # - services-test-api
      # - gateway-web-client
      # - usersdb
      # - mongo

  gateway-web-client:
    container_name: gateway-web-client
    image: gateway-web-client:prod
    build:
      context: ./gateway/web-client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - services-test-api

  services-test-api:
    container_name: services-test-api
    image: services-test-api:prod
    build:
      context: ./services/test-api
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=usersdb
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - 7100:80
    depends_on:
      - usersdb

  usersdb:
    container_name: usersdb
    image: mongo-express
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - testdata:/data/db
    ports:
      - 8081:80

  mongo:
    image: mongo
    container_name: seesee-mongo
    restart: always
    ports:
      - 27107:80
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD

volumes:
  testdata:
