version: '2'
services:
  seesee-client:
    image: seesee-client
    restart: always
    ports:
      - '3000:3000'
    working_dir: /opt/seesee
    volumes:
      - ./seesee-client:/opt/seesee
    entrypoint: ['yarn', 'start']
    links:
      - api
    networks:
      - seesee-network

  listings-service:
    image: listings-service
    restart: always
    ports:
      - '3000:3000'
    working_dir: /opt/seesee
    volumes:
      - ./seesee-client:seesee-client
      - ./seesee-client/node_modules
    depends_on:
      - mongodb
    links:
      - users-service
    networks:
      - seesee-network

  users-service:
    image: users-service
    restart: always
    ports:
      - '9000:9000'
    working_dir: /opt/seesee
    volumes:
      - ./users-service:/users-service
      - /users-service/node_modules
    depends_on:
      - mongodb
    networks:
      - seesee-network

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - seesee-network

networks:
  seesee-network:
    driver: bridge
