version: '3'
services:
  
  users_service:
    container_name: users_service
    build: ./services/users/
    environment:
      DB_URI: 'mysql://root:password@users_service_db/db?charset=UTF8'
      SERVICE_NAME: users_service
    ports:
      - '7101:7101'
    links:
      - users_service_db

  users_service_db:
    container_name: users_service_db
    image: 'mysql:5.7.20'
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '0.0.0.0:7201:3306'
      
  listings_service:
    container_name: listings_service
    build: ./services/listings/
    environment:
      DB_URI: 'mysql://root:password@listings_service_db/db?charset=UTF8'
      SERVICE_NAME: listings_service
    ports:
      - '7100:7100'
    links:
      - listings_service_db

  listings_service_db:
    container_name: listings_service_db
    image: 'mysql:5.7.20'
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '0.0.0.0:7200:3306'

  api_gateway:
    container_name: api_gateway
    build: ./services/nginx
    restart: always
    depends_on:
      - users_service
      - listings_service
    ports:
      - 80

  client_api:
    container_name: client_api
    build: ./gateway/client/
    environment:
      LISTINGS_SERVICE_URI: 'http://listings_service:7100'
      USERS_SERVICE_URI: 'http://users_service:7101'
    ports:
      - '7000:7000'
    links:
      - listings_service
      - users_service
    depends_on:
      - listings_service
      - users_service

  datadog:
    links:
      - api_gateway
      - users_service_db
      - listings_service_db
    image: 'datadog/agent:latest'
    environment:
      DD_API_KEY: d9ea5db53324fb66e0be658b2c66da8c
