version: '3.8'

services:
  proxy:
    restart: always
    build:
      context: proxy
      dockerfile: Dockerfile.dev
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx:/etc/nginx
      - ./proxy/certs:/etc/ssl/certs
      - ./proxy/lua:/usr/local/openresty/nginx/lua
    networks:
      - back-tier
    depends_on:
      - users

  users:
    restart: always
    build:
      context: users
      dockerfile: Dockerfile.dev
    container_name: users
    volumes:
      - ./users:/home/node/app
      - users-nm:/home/node/app/node_modules
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
    name: back-tier

volumes:
  users-nm:
