version: '3.8'

services:
  gateway:
    hostname: gateway
    build:
      context: gateway
      dockerfile: Dockerfile
    restart: always
    container_name: gateway
    image: danydodson/ss-gateway
    ports:
      - 80:80
    volumes: 
      - ./gateway/nginx:/etc/nginx
      - ./gateway/certs:/etc/ssl/certs
      - ./gateway/lua:/usr/local/openresty/nginx/lua
    networks:
      - back-tier
    depends_on:
      - users-api
      - posts-api

  users-api:
    build:
      context: users-api
      dockerfile: Dockerfile
    restart: always
    container_name: users-api
    image: danydodson/ss-users-api
    volumes:
      - ./users-api:/home/node/app
      - users-nm:/home/node/app/node_modules
    networks:
      - back-tier

  posts-api:
    build:
      context: posts-api
      dockerfile: Dockerfile
    restart: always
    container_name: posts-api
    image: danydodson/ss-posts-api
    volumes:
      - ./posts-api:/home/node/app
      - users-nm:/home/node/app/node_modules
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
    name: back-tier

volumes: 
  users-nm:
  posts-nm: