version: "3.8"
services:

  nginx_proxy:
    container_name: nginx_proxy
    # build: ./gateway/nginx_proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
  
  nginx_letsencrypt:
    container_name: nginx_letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx_proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx_proxy

  web_client:
    container_name: web_client
    build: ./gateway/web_client
    volumes:
      - ./gateway/web_client:/usr/src/app
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=seesee.com
      - LETSENCRYPT_HOST=seesee.com
      - LETSENCRYPT_EMAIL=dany@dany.codes
    ports:
      - 3000:80
    depends_on:
      - users_api

  users_api:
    container_name: users_api
    build: ./services/users/api
    restart: unless-stopped
    # volumes:
      # - /usr/src/app/node_modules
      # - ./services/users/api:/usr/src/app
    environment:
      - MONGO_USERNAME=dany
      - MONGO_PASSWORD=password
      - MONGO_DB=seesee-users-data
      - MONGO_HOSTNAME=users_mongo
    ports:
      - 7000:7000
    logging:
      options:
        max-size: "4m"
        max-file: "10"
    depends_on:
      - users_mongo

  users_mongo:
    container_name: users_mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - users_db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dany
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27107:27107
    
volumes:
  conf:
  vhost:
  html:
  certs:
  users_db:

networks:
  default:
    external:
      name: nginx-proxy