version: '3'
services:

  gateway_proxy:
    build: gateway/proxy
    container_name: gateway_proxy
    restart: always
    ports:
      - '3050:80'
    depends_on:
      - gateway_client
      - users_service
      - profiles_service
      - posts_service
    networks:
      - apis_network
      
  gateway_client:
    build: gateway/client
    container_name: gateway_client
    restart: always
    volumes:
      - /home/node/app/node_modules
      - './gateway/client:/home/node/app'
    networks:
      - apis_network

  users_service:
    build: services/users
    container_name: users_service
    volumes:
      - /home/node/app/node_modules
      - './services/users:/home/node/app'
    networks:
      - apis_network

  profiles_service:
    build: services/profiles
    container_name: profiles_service
    volumes:
      - /home/node/app/node_modules
      - './services/profiles:/home/node/app'
    networks:
      - apis_network

  posts_service:
    build: services/posts
    container_name: posts_service
    volumes:
      - /home/node/app/node_modules
      - './services/posts:/home/node/app'
    networks:
      - apis_network

networks:
  apis_network: null
