version: "3.7"

services:

  gateway-nginx-proxy:
    container_name: gateway-nginx-proxy
    image: nginx:stable-alpine
    build:
      context: ./gateway/nginx-proxy/.devcontainer
      dockerfile: Dockerfile.dev
    volumes:
      - ./gateway/nginx-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/.gitconfig:/home/node/.gitconfig
    ports:
      - 8080:8080
    networks:
      - test-network

  # gateway-web-client:
  #   image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-12
  #   build:
  #     context: ./gateway/web-client/.devcontainer
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./gateway/web-client:/home/node/workspace
  #     - ~/.gitconfig:/home/node/.gitconfig
  #   ports:
  #     - 3030:3030
  #   command: sleep infinity
  #   container_name: gateway-web-client

  # services-test-api:
  #   image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-12
  #   build:
  #     context: ./services/test-api/.devcontainer
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./services/test-api:/home/node/workspace
  #     - ~/.gitconfig:/home/node/.gitconfig
  #   ports:
  #     - 7000:7000
  #   command: sleep infinity
  #   container_name: services-test-api

  # web-gallery-pwa:
  #   build:
  #     context: ./web/gallery-pwa/.devcontainer
  #     dockerfile: Dockerfile.dev
  #   image: web-gallery-pwa:development
  #   volumes:
  #     - ./web/gallery-pwa:/home/node/workspace
  #     - ~/.gitconfig:/home/node/.gitconfig
  #   ports:
  #     - 3000:3000
  #   command: sleep infinity
  #   container_name: web-gallery-pwa

# volumes:
#   test-data:

networks:
  test-network: