version: '3.7'

services:
  
  gateway-nginx-proxy:
    container_name: gateway-nginx-proxy
    image: nginx
    build:
      context: ./gateway/nginx-proxy
      dockerfile: Dockerfile
    ports:
      - '8080:80'

  # gateway-web-client:
  #   container_name: gateway-web-client
  #   image: gateway-web-client:prod
  #   build:
  #     context: ./gateway/web-client
  #     dockerfile: Dockerfile
    # ports:
      # - '3030:80'

  # services-gallery-api:
  #   container_name: services-gallery-api
  #   image: services-gallery-api:prod
  #   build:
  #     context: ./services/gallery-api
  #     dockerfile: Dockerfile
  #   ports:
  #     - 6000:6000

  services-test-api:
    container_name: services-test-api
    image: services-test-api:prod
    build:
      context: ./services/test-api
      dockerfile: Dockerfile
    ports:
      - 7100:80

  # services-users-api:
  #   container_name: services-users-api
  #   image: services-users-api:prod
  #   build:
  #     context: ./services/users-api
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:8000

  # web-gallery-pwa:
  #   container_name: web-gallery-pwa
  #   image: web-gallery-pwa:prod
  #   build:
  #     context: ./web/gallery-pwa
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3030:80

  # subscribers-rabbit:
  #   hostname: rabbit
  #   image: rabbitmq:latest
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=mypass
  #   ports:
  #     - '5672:5672'

# networks:
# seeseenetwork:
# web-gallery-pwa-network:
#   external:
#     name: web-gallery-pwa
# services-test-api-network:
#   external:
#     name: services-test-api
