version: '3'
services:
  postgres:
    image: 'postgres:latest'

  redis:
    image: 'redis:latest'

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  server-service:
    build:
      dockerfile: Dockerfile.dev
      context: ./server-service
    volumes:
      - /app/node_modules
      - ./server-service:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432

  seesee-client:
    build:
      dockerfile: Dockerfile.dev
      context: ./seesee-client
    volumes:
      - /app/node_modules
      - ./seesee-client:/app

  redis-service:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./redis-service
    volumes:
      - /app/node_modules
      - ./redis-service:/app
