version: '2.1'
services:
  api-gateway:
    container_name: api-gateway
    build: './api-gateway'
    ports:
      - '3002:3000'
    depends_on:
      - listings-service
    networks:
      - platform-network

  listings-service:
    container_name: listings-service
    build: './listings-service'
    environment:
      - MONGO_DB_URI=mongodb://db/seesee-listings
    depends_on:
      - db
    ports:
      - '7100:7100'
    networks:
      - platform-network

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./seesee-client/public:/usr/share/nginx/html:ro
      # - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - platform-network

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - nginx
    networks:
      - platform-network

  db:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'

networks:
  platform-network:
