# check for openresty network bottleneck

version: '3.8'

networks:
  back-tier:
    driver: bridge
    name: seesee-back

services:
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    restart: always
    container_name: seesee-gateway
    image: danydodson/seesee-gateway
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ./gateway/.env
    volumes:
      - './gateway/nginx/nginx.conf:/nginx.conf'
      - './gateway/lua/test.lua:/test.lua'
      - './gateway/lua/req.lua:/req.lua'
      - './gateway/lua/sign.lua:/sign.lua'
      - './gateway/lua/verify.lua:/verify.lua'
    networks:
      - back-tier
    depends_on:
      - users-api
      - posts-api
  
  users-api:
    build:
      context: users-api
      dockerfile: Dockerfile
    restart: always
    container_name: seesee-users-api
    image: danydodson/seesee-users-api
    env_file:
      - ./users-api/.env
    volumes:
      - './users-api:/usr/src/app'
      - /usr/src/app/node_modules
    networks:
      - back-tier

  posts-api:
    build:
      context: posts-api
      dockerfile: Dockerfile
    restart: always
    container_name: seesee-posts-api
    image: danydodson/seesee-posts-api
    env_file:
      - ./posts-api/.env
    volumes:
      - './posts-api:/usr/src/app'
      - /usr/src/app/node_modules
    networks:
      - back-tier