version: '3.8'
services:

  # ==========================================#
  #  services/nginx-proxy                     #
  # ==========================================# 

  nginx_proxy:
    container_name: nginx_proxy
    image: nginx
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
    ports:
      - 80:80
      - 443:443
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: always
  
  # ==========================================#
  #  services/nginx docker-gen                #
  # ==========================================# 
  
  docker_gen:
    container_name: docker_gen
    image: jwilder/docker-gen
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_certs:/etc/nginx/certs:ro
      - ./services/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup nginx_proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    depends_on:
      - nginx_proxy
    restart: always

  # ==========================================#
  #  services/nginx-letsencrypt               #
  # ==========================================#

  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx_proxy
      - docker_gen
    restart: always

  # ==========================================#
  #  gateway/client                           #
  # ==========================================#

  client_gateway:
    container_name: client_gateway
    build: 
      context: .
      dockerfile: ./gateway/client/Dockerfile
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=gallery.seesee.space
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=gallery.seesee.space
      - LETSENCRYPT_EMAIL=dany@dany.codes
      - USERS_SERVICE_URI=http://users_service:7101
      - LISTINGS_SERVICE_URI=http://listings_service:7100
      - ./gateway/client:/usr/src/app
    ports:
      - 7000:7000
    # depends_on:
    #   - users_service
    #   - listings_service


  # ==========================================#
  #  services/users-service                   #
  # ==========================================#

  users_service:
    container_name: users_service
    build:
      context: .
      dockerfile: ./services/users/Dockerfile
    environment:
      - DB_URI=mysql://root:password@users_service_db/db?charset=UTF8
    volumes:
      - ./services/users-service:/usr/src/app
    ports:
      - 7101:7101
    depends_on:
      - users_service_db

  # ==========================================#
  #  services/users-data                      #
  # ==========================================#

  users_service_db:
    container_name: users_service_db
    image: mysql:5.7.20
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - 7201:3306
      # - 0.0.0.0:7201:3306

  # ==========================================#
  #  services/listings-service                #
  # ==========================================#

  listings_service:
    container_name: listings_service
    build:
      context: .
      dockerfile: ./services/listings/Dockerfile
    environment:
      - DB_URI=mysql://root:password@listings_service_db/db?charset=UTF8
    volumes:
      - ./services/listings-service:/usr/src/app
    ports:
      - 7100:7100
    depends_on:
      - listings_service_db

  # ==========================================#
  #  services/listings-data                   #
  # ==========================================#

  listings_service_db:
    container_name: listings_service_db
    image: mysql:5.7.20
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - 7200:3306
      # - 0.0.0.0:7200:3306
      
  # ==========================================#
  #  services/users                           #
  # ==========================================#

  # auth_service:
  #   container_name: auth_service
  #   image: danydodson/auth_service
  #   build:
  #     context: .
  #     dockerfile: 'Dockerfile'
  #   env_file: ./gateway/passport/.env
  #   environment:
  #     - MONGO_HOSTNAME=auth_data
  #     - MONGO_USERNAME=$MONGO_USERNAME
  #     - MONGO_PASSWORD=$MONGO_PASSWORD
  #     - MONGO_DB=$MONGO_AUTH_DB
  #   volumes:
  #     - /usr/src/app/node_modules
  #     - ./gateway/passport:/usr/src/app
  #   ports:
  #     - '80:5000'
  #   depends_on:
  #     - auth_data
  #   command: ./wait-for.sh auth_data:27017 -- /home/node/app/node_modules/.bin/nodemon src/index.js

  # ==========================================#
  #  gateway/passport                         #
  # ==========================================#

  # auth_data:
  #   container_name: auth_data
  #   image: mongo
  #   env_file: ./gateway/passport/.env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  #   volumes:
  #     - auth_db_vol:/data/db
  #   ports:
  #     - '27018:27018'
  #   restart: unless-stopped
  
  # ==========================================#
  #  services/users/api                       #
  # ==========================================#

  # users_service:
  #   container_name: users_service
  #   build: ./services/users/api
  #   env_file: ./services/users/api/.env
  #   environment:
  #     - MONGO_HOSTNAME=users_data
  #     - MONGO_USERNAME=$MONGO_USERNAME
  #     - MONGO_PASSWORD=$MONGO_PASSWORD
  #     - MONGO_DB=$MONGO_USERS_DB
  #   volumes: 
  #     - /usr/src/app/node_modules
  #     - ./services/users/api:/usr/src/app
  #   ports:
  #     - 7000:7000
  #   logging:
  #     options:
  #       max-size: "4m"
  #       max-file: "10"
  #   depends_on:
  #     - users_data
  #   restart: unless-stopped

  # ==========================================#
  # services/users/db                         #
  # ==========================================#

  # users_data:
  #   container_name: users_data
  #   image: mongo
  #   ports:
  #     - 27107:27107
  #   env_file: ./services/users/api/.env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  #   volumes:
  #     - users_db_vol:/data/db
  #   restart: unless-stopped

  # ==========================================#
  #  services/gallery/api                     #
  # ==========================================#

  # gallery_service:
  #   container_name: gallery_service
  #   build: ./services/gallery/api
  #   env_file: ./services/gallery/api/.env
  #   volumes:
  #     - /usr/src/app/node_modules
  #     - ./services/users/api:/usr/src/app
  #   environment:
  #     - MONGO_HOSTNAME=gallery_data
  #     - MONGO_USERNAME=$MONGO_USERNAME
  #     - MONGO_PASSWORD=$MONGO_PASSWORD
  #     - MONGO_DB=$MONGO_GALLERY_DB
  #   ports:
  #     - 7000:7000
  #   logging:
  #     options:
  #       max-size: "4m"
  #       max-file: "10"
  #   depends_on:
  #     - gallery_data
  #   restart: unless-stopped

  # ==========================================#
  # services/gallery/db                       #
  # ==========================================#

  # gallery_data:
  #   container_name: gallery_data
  #   image: mongo
  #   env_file: ./services/gallery/api/.env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
  #   volumes:
  #     - gallery_db_vol:/data/db
  #   ports:
  #     - 27107:27107
  #   restart: unless-stopped

  # ==========================================#
  # subscribers/rabbitmq                      #
  # ==========================================#

  # rabbitmq:
  #   container_name: rabbitmq
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   env_file: ./subscribers/rabbitmq/.env
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  #   volumes:
  #     - ./subscribers/rabbitmq/etc/:/etc/rabbitmq/
  #     - ./subscribers/rabbitmq/data/:/var/lib/rabbitmq/
  #     - ./subscribers/rabbitmq/logs/:/var/log/rabbitmq/
      
  # ==========================================#
  #  services/mongo_express                   #
  # ==========================================#

  # mongo_express:
  #   image: mongo-express
  #   container_name: mongo_express
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./.docker/mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
  #   env_file: ./services/users/api/.env
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
  #     ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    # depends_on:
      # - auth_service
      # - users_service
      # - gallery_service

  # ==========================================#
  #  services/grafana                         #
  # ==========================================#

  grafana:
    container_name: grafana
    image: grafana/grafana
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=graf.seesee.space
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=graf.seesee.space
      - LETSENCRYPT_EMAIL=dany@dany.codes
    restart: always
  
  # ==========================================#
  #  utilities/proxy_tunnel                   #
  # ==========================================#

  # proxy_tunnel:
  #   container_name: proxy_tunnel
  #   image: danydodson/seesee_proxy_tunnel
  #   ports:
  #     - "2222:22"
  #   expose:
  #     - "2222"
  #   environment:
  #     - VIRTUAL_HOST=dev.seesee.space
  #     - LETSENCRYPT_HOST=dev.seesee.space

# ==========================================#
#  global volumes                           #
# ==========================================#

volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  nginx_certs:
  
# ==========================================#
#  global networks                          #
# ==========================================#
  
networks:
  default:
    external:
      name: services_network