version: '3.8'

networks:
  back_tier:
    driver: bridge
    name: seesee-ms-back

services:
  gateway:
    build: 
      - context: gateway
      - dockerfile: Dockerfile
    image: seesee-gateway-service
    restart: always
    ports:
      - 80:80
    networks:
      - back_tier