version: '3.7'

services:

  gateway-nginx-proxy:
    container_name: gateway-nginx-proxy
    image: gateway-nginx-proxy:production
    build: 
      context: ./gateway/nginx-proxy
      dockerfile: Dockerfile
    volumes:
      - ./gateway/nginx-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ~/.gitconfig:/home/node/.gitconfig
    ports:
      - 80:80
      - 443:443
    restart: always
    # links:
    #   - gateway-web-client
    #   - services-gallery-api
    #   - services-test-api
    #   - services-users-api
    #   - web-gallery-pwa

  gateway-web-client:
    container_name: gateway-web-client
    image: gateway-web-client:production
    build: 
      context: ./gateway/web-client
      dockerfile: Dockerfile
    volumes:
      - ./gateway/web-client:/home/node/workspace
      - ~/.gitconfig:/home/node/.gitconfig
    ports:
      - 3030:3030

  services-gallery-api:
    container_name: services-gallery-api
    image: services-gallery-api:production
    build: 
      context: ./services/gallery-api
      dockerfile: Dockerfile
    volumes:
      - ./services/gallery-api:/home/node/workspace
      - ~/.gitconfig:/home/node/.gitconfig
    ports:
      - 6000:6000

  services-test-api:
    container_name: services-test-api
    image: services-test-api:production
    build: 
      context: ./services/test-api
      dockerfile: Dockerfile
    volumes:
      - node_modules:/home/node/workspace/node_modules
    ports:
      - 7000:7000

  services-users-api:
    container_name: services-users-api
    image: services-users-api:production
    build: 
      context: ./services/users-api
      dockerfile: Dockerfile
    volumes:
      - ./services/users-api:/home/node/workspace
      - ~/.gitconfig:/home/node/.gitconfig
    ports:
      - 8000:8000
  
  web-gallery-pwa:
    container_name: web-gallery-pwa
    image: web-gallery-pwa:production
    build: 
      context: ./web/gallery-pwa
      dockerfile: Dockerfile
    ports:
      - 3030:3000

volumes:
  node_modules: