version: '3.7'

services:

  gateway-nginx-proxy:
    container_name: gateway-nginx-proxy
    image: gateway-nginx-proxy:prod
    build:
      context: ./gateway/nginx-proxy
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - test_network
    depends_on:
      - gateway-web-client
      - services-test-api

  gateway-web-client:
    container_name: gateway-web-client
    image: gateway-web-client:prod
    build:
      context: ./gateway/web-client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - test-api
    networks:
      - test_network

  services-test-api:
    container_name: services-test-api
    image: services-test-api:prod
    build:
      context: ./services/test-api
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=data-test-db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - 8081:8081
    depends_on:
      - data-test-db

  data-test-db:
    container_name: data-test-db
    image: mongo-express
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - test-data:/data/db
    ports:
      - 8081:8081
    networks:
      - test_network

  mongo:
    container_name: data-mongodb
    image: mongo
    restart: always
    ports:
      - 27107:27107
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD

volumes:
  test-data:

networks:
  test_network:
  
