version: '3'
services:
  postgres-server:
    container_name: postgres-server
    image: 'postgres'
    networks:
      - seesee-platform

  redis-server:
    container_name: redis-server
    image: 'redis'
    networks:
      - seesee-platform

  nginx:
    container_name: nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
    networks:
      - seesee-platform

  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='postgres'
      - POSTGRES_DB='postgres'
      - REDIS_HOST='redis-server'
      - REDIS_PORT=6379
    networks:
      - seesee-platform

  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - seesee-platform

  worker:
    container_name: worker
    build:
      dockerfile: Dockerfile
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    networks:
      - seesee-platform

networks:
  seesee-platform:
