version: '3.1'

services:
  gateway:
    container_name: gateway
    build: .
    volumes:
      - ./gateway:/etc/nginx/:ro
      # - ./gateway/logs/:/var/log/nginx/ # Uncomment to save logs to respective files instead of the STDOUT
