version: "3.7"

services:

  gateway-nginx-proxy:
    container_name: gateway-nginx-proxy
    build:
      context: ./gateway/nginx-proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - gateway-web-client
      - services-test-api

  gateway-web-client:
    build:
      context: ./gateway/web-client
      dockerfile: Dockerfile
    container_name: gateway-web-client
    expose:
      - 3000

  services-test-api:
    container_name: services-test-api
    build:
      context: ./services/test-api
      dockerfile: Dockerfile
    expose:
      - 7000
    env_file: ./services/test-api/docker.env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=services-test-data
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    depends_on:
      - services-test-data

  services-test-data:
    container_name: services-test-data
    image: mongo
    restart: unless-stopped
    env_file: ./services/test-api/docker.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - test-db:/data/db
    ports:
      - 0.0.0.0:27107:7000

volumes:
  test-db:

# networks:
#   test-network:
#   auth-network:
#   users-network:
#   listings-network: