version: '3'
services:
  gateway_proxy:
    build: gateway/proxy
    container_name: gateway_proxy
    restart: always
    ports:
      - '3050:80'
    volumes:
      - './gateway/proxy/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './gateway/proxy/conf.d/user.conf:/etc/nginx/conf.d/user.conf:ro'
    depends_on:
      - gateway_client
      - users_service
    networks:
      - api_network
  gateway_client:
    build: gateway/client
    container_name: gateway_client
    restart: always
    volumes:
      - /home/node/app/node_modules
      - './gateway/client:/home/node/app'
    networks:
      - api_network
  users_service:
    build: services/users
    container_name: users_service
    volumes:
      - /home/node/app/node_modules
      - './services/users:/home/node/app'
    networks:
      - api_network
networks:
  api_network: null
