version: '3.8'

services:
  nginx-ui:
    image: schenkd/nginx-ui:latest
    container_name: nginx-ui
    ports:
      - 8080:8080
    volumes:
      - nginx:/etc/nginx
      
  proxy:
    restart: always
    image: danydodson/ss-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./proxy/nginx:/etc/nginx
      - ./proxy/certs:/etc/ssl/certs
      - ./proxy/lua:/usr/local/openresty/nginx/lua
    networks:
      - back-tier
    depends_on:
      - users

  users:
    restart: always
    image: danydodson/ss-users
    container_name: users
    volumes:
      - ./users:/home/node/app
      - users-nm:/home/node/app/node_modules
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
    name: back-tier

volumes: 
  users-nm: