version: '3.8'
services:

  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    restart: always
    container_name: gateway
    image: danydodson/ss-gateway
    ports:
      - '80:80'
    env_file:
      - ./gateway/.env
    volumes:
      - './gateway/nginx:/etc/nginx/conf.d'
      - './gateway/lua:/usr/local/openresty/lualib/conf'
    networks:
      - back-tier
    depends_on:
      - users-api
      - posts-api

  users-api:
    build:
      context: users-api
      dockerfile: Dockerfile
    restart: always
    container_name: users-api
    image: danydodson/ss-users-api
    env_file:
      - ./users-api/.env
    volumes:
      - './users-api:/usr/src/app'
      - /usr/src/app/node_modules
    networks:
      - back-tier

  posts-api:
    build:
      context: posts-api
      dockerfile: Dockerfile
    restart: always
    container_name: posts-api
    image: danydodson/ss-posts-api
    env_file:
      - ./posts-api/.env
    volumes:
      - './posts-api:/usr/src/app'
      - /usr/src/app/node_modules
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
    name: seesee-back