version: '3.8'

services:
  gateway:
    hostname: localhost
    build:
      context: gateway
      dockerfile: Dockerfile
    restart: always
    container_name: gateway
    image: danydodson/ss-gateway
    ports:
      - 80:80
    env_file:
      - ./gateway/.env
    environment:
      - USERS_API=http://users-api
      - POSTS_API=http://posts-api
      - REDIS_AUTH=http://redis-auth
    volumes: 
      - ./gateway/logs/:/var/log/nginx/
      - ./gateway/conf:/etc/nginx/conf/:ro
      - ./gateway/servers/:/etc/nginx/servers/:ro
    networks:
      - back-tier
    depends_on:
      - users-api
      - posts-api
  
  users-api:
    build:
      context: users-api
      dockerfile: Dockerfile
    restart: always
    container_name: users-api
    image: danydodson/ss-users-api
    env_file:
      - ./users-api/.env
    volumes:
      - ./users-api:/home/node/app
      - users-nm:/home/node/app/node_modules
    networks:
      - back-tier

  posts-api:
    build:
      context: posts-api
      dockerfile: Dockerfile
    restart: always
    container_name: posts-api
    image: danydodson/ss-posts-api
    env_file:
      - ./posts-api/.env
    volumes:
      - ./posts-api:/home/node/app
      - users-nm:/home/node/app/node_modules
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
    name: back-tier

volumes: 
  pwa-nm:
  users-nm:
  posts-nm: