FROM openresty/openresty:alpine-fat

COPY certs/certificate.crt /etc/ssl/certificate.crt
COPY certs/private.key /etc/ssl/private.key

# COPY conf/nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
# COPY conf/default.conf /etc/nginx/conf.d/default.conf
# COPY html/* /usr/local/openresty/nginx/html/

RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-jwt

ENTRYPOINT ["/usr/local/openresty/bin/openresty", "-g", "daemon off;", "-c", "/nginx.conf"]