version: '3'
services:
  #
  users_api:
    container_name: users_api
    image: danydodson/users_api:latest
    build:
      context: .
      dockerfile: 'Dockerfile'
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=usersdb
      - MONGO_DB=$MONGO_DB
    ports:
      - '5000:5000'
    depends_on:
      - users_db
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - users_network
    command: ./wait-for.sh users_db:27017
    # command: ./wait-for.sh users_db:27017 -- /home/node/app/node_modules/.bin/nodemon v1/index.js
  #
  users_db:
    container_name: users_db
    image: mongo:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - users_db_vol:/data/db
    ports:
      - '27017:27017'
    networks:
      - users_network
#
networks:
  users_network:
    driver: bridge
#
volumes:
  users_db_vol:
  node_modules:
