# Base
version: '3.4'

services:
  cart-api:
    image: seesee/cart-api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Cart/Cart.API/Dockerfile
    depends_on:
      - cartdata
      - identity-api
      - rabbitmq

  listings-api:
    image: seesee/listings-api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Listings/Listings.API/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq

  marketing-api:
    image: seesee/marketing-api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Marketing/Marketing.API/Dockerfile
    depends_on:
      - sqldata
      - nosqldata
      - identity-api
      - rabbitmq

  webmvc:
    image: seesee/webmvc:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebMVC/Dockerfile
    depends_on:
      - listings-api
      - ordering-api
      - identity-api
      - cart-api
      - marketing-api

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest

  nosqldata:
    image: mongo

  cartdata:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management
