FROM node:7.8

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR '/home/node/app'
COPY package*.json .
RUN npm install

ENV PORT 3001
EXPOSE $PORT

CMD ['npm', 'run', 'docker-test']