version: '3'
services:

  nginx:
    container_name: gallery_pwa
    # image: nginx
    build: .
    restart: unless-stopped 
    environment:
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=dany@dany.codes
    expose:
      - 3030
    volumes:
      - ./build:/usr/share/nginx/html
    logging:
      options:
        max-size: "4m"
        max-file: "10"

networks:
  default:
    external:
      name: nginx-proxy

