version: '3'

services:
  reverse-proxy:
    image: reverse-proxy
    restart: always
    ports:
      - 80:80
      - 443:443

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    networks:
      - nginx-network
    depends_on:
      - reverse-proxy

networks:
  nginx-network:
    driver: bridge
