version: '3.8'

services:

  # ==========================================#
  # subscribers/rabbitmq                      #
  # ==========================================#

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./subscribers/rabbitmq/etc/:/etc/rabbitmq/
      - ./subscribers/rabbitmq/data/:/var/lib/rabbitmq/
      - ./subscribers/rabbitmq/logs/:/var/log/rabbitmq/
  