version: '3.8'
services:

  # ==========================================#
  #  certbot                                  #
  # ==========================================#

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - web_root:/var/www/html
    # depends_on:
      # - nginx_server
    command: certonly --webroot --webroot-path=/var/www/html --email dany@dany.codes --agree-tos --no-eff-email --staging -d seesee.space  -d www.seesee.space
    # command: certonly --webroot --webroot-path=/var/www/html --email dany@dany.codes --agree-tos --no-eff-email --force-renewal -d seesee.space  -d www.seesee.space

  # ==========================================#
  #  services/nginx:proxy                     #
  # ==========================================# 

  nginx_proxy:
    container_name: nginx_proxy
    image: nginx
    restart: always
    volumes:
      - nginx_conf_vol:/etc/nginx/conf.d
      - nginx_vhost_vol:/etc/nginx/vhost.d
      - nginx_html_vol:/usr/share/nginx/html
      - nginx_certs_vol:/etc/nginx/certs:ro
    ports:
      - 80:80
      - 443:443
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  
  # ==========================================#
  #  services/nginx:docker-gen                #
  # ==========================================# 
  
  nginx_docker_gen:
    container_name: nginx_docker_gen
    image: jwilder/docker-gen
    restart: always
    volumes:
      - nginx_conf_vol:/etc/nginx/conf.d
      - nginx_vhost_vol:/etc/nginx/vhost.d
      - nginx_certs_vol:/etc/nginx/certs:ro
      - ./services/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup nginx_proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    depends_on:
      - nginx_proxy

  # ==========================================#
  #  services/nginx:letsencrypt               #
  # ==========================================#

  nginx_letsencrypt:
    container_name: nginx_letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx_proxy
      - nginx_docker_gen
      
  

# ==========================================#
#  global volumes                           #
# ==========================================#

volumes:
  nginx_conf_vol:
  nginx_vhost_vol:
  nginx_html_vol:
  nginx_certs_vol:
  gateway_passport_data_vol:
  
# ==========================================#
#  global networks                          #
# ==========================================#
  
networks:
  default:
    external:
      name: services_network