version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - react-app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test-network
    ports:
      - 80:80

  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: node
    container_name: react-app
    volumes:
      - ./:/code/
    environment:
      - FLASK_APP=/code/main.py
    command: flask run --host=0.0.0.0
    networks:
      test-network:
        aliases:
          - flask-app

networks:
  test-network:
