FROM openresty/openresty:alpine-fat

RUN apk add --no-cache git && \
  rm -rf /etc/nginx/* && \
  mkdir -p /var/log/nginx

COPY nginx/* /etc/nginx/
COPY lua/* /usr/local/openresty/nginx/lua/
# COPY lua/* /usr/local/openresty/lualib/

RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-jwt
RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-cookie

RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stdout /var/log/nginx/error.log

# ENV PATH='/usr/local/openresty/nginx/lua:${PATH}'

ENTRYPOINT ["/usr/local/openresty/bin/openresty", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]