# will be moved into root directory
version: 0.0
os: linux
files:
  - source: /
    destination: /usr/src/seesee-platform
hooks:
  pre-install:
    - location: users-service/aws/codedeploy/pre-install/0_stop-process.sh
      timeout: 300
      runas: root
    - location: users-service/aws/codedeploy/pre-install/1_remove-previous.sh
      timeout: 300
      runas: ec2-user
  post-install:
    - location: users-service/aws/codedeploy/post-install/0_change-permissions.sh
      timeout: 300
      runas: root
    - location: users-service/aws/codedeploy/post-install/1_install-packages.sh
      timeout: 300
      runas: ec2-user
    - location: users-service/aws/codedeploy/post-install/2_run-migrations.sh
      timeout: 300
      runas: ec2-user
    - location: users-service/aws/codedeploy/post-install/3_build-bundle.sh
      timeout: 300
      runas: ec2-user
  start-application:
    - location: users-service/aws/codedeploy/start-application.sh
      timeout: 300
      runas: root
