  subscribers_rabbitmq:
    image: rabbitmq:3-management-alpine 
    container_name: subscribers_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: toor
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - secure_network